name: docker-tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: build image + run tests
      run: docker build -t cardvalidation-tests .

    - name: copy test results out
      run: |
        cid=$(docker create cardvalidation-tests)
        docker cp "$cid":/artifacts ./artifacts
        docker rm "$cid"

    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./artifacts
